### ISSUE TITLE
How to generate diagram with schemacrawler-maven-plugin?

### ISSUE THREAD

**Issue by sualeh** [sualeh/SchemaCrawler-Report-Maven-Plugin#1]
_From @jeffjensen on September 20, 2015 16:29_

I am struggling to find the correct configuration between pom and property files to generate a diagram.
Is it possible to do so or is the Maven plugin not able to generate the diagram?

I'm using these versions:
```
<groupId>net.sourceforge.schemacrawler</groupId>
<artifactId>schemacrawler-maven-plugin</artifactId>
<version>9.5</version>
```
```
<groupId>us.fatehi</groupId>
<artifactId>schemacrawler</artifactId>
<version>12.06.03</version>        (the latest version I found that works with Java 7)
```

_Copied from original issue: sualeh/SchemaCrawler#11_

**Comment by sualeh** [comment]
Jeff, unfortunately I am not maintaining the SchemaCrawler Maven Plugin too much, and it is a separate project from this one. Please check if you can execute SchemaCrawler as a Java process from your Maven project. If you can, then I would love it if you can share what you find. Otherwise, I can certainly use your help on the  SchemaCrawler Maven Plugin, if you are so inclined.

**Comment by sualeh** [comment]
_From @jeffjensen on September 22, 2015 19:4_

Currently, it looks like the plugin correctly runs SchemaCrawler, but the resulting PNG is in the generated page as file contents vs an image (looks like gibberish characters).

I hope to have some time soon to try what you suggest.  Improving the plugin is ideal, but using exec may work well enough.

**Comment by sualeh** [comment]
Try using the htmlx output format. I will take a look at the plugin code when I get a chance.

**Comment by sualeh** [comment]
_From @jeffjensen on September 23, 2015 3:32_

Thanks for the tip.  Your suggestion goes directly to my original question: I don't know where to specify the output format for the plugin.
  * The plugin does not have an attribute in `<configuration>`.
  * The plugin does not appear to see the schemacrawler.config.properties file.

**Comment by sualeh** [comment]
@jeffjensen, I have moved this issue to a new repository for the SchemaCrawler Report Maven Plugin.

**Comment by jeffjensen** [comment]
Thank you!

**Comment by sualeh** [comment]
Jeff, I have released an updated version of the SchemaCrawler Report Maven Plugin. It requires Java 8, and uses SchemaCrawler 14.03.03 by default. It has a new groupId, "us.fatehi", to be consistent with the main SchemaCrawler jar. The plugin now supports "outputformat", and can generate image files. You can find it on Maven Central. Please try it out, and let me know.

**Comment by DanielFran** [comment]
@jeffjensen @schemacrawler Any example how to use this plugin?
